// import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


// const sidebars = {
// docs: [
//     {
//       type: "category",
//       label: "Admin",
//       items: ["admin/project-guide"],
//     },
//     {
//       type: "category",
//       label: "User",
//       items: ["user/project-guide"],
//     },
//   ],

//   keypointsSidebar: [
//     'process',
//     {
//       type: 'category',
//       label: 'Key Points',
//       items: ['key-points/brd-key-points',
//         'key-points/srs-key-points',
//       'key-points/stakeholder-discussions',
//     'key-points/scope-timeline',
//     'key-points/ui-ux-references',
//     'key-points/outcome'],
//     },
//     'key-points/phase-2-design-specification',
//     'node-js/node-js-project-testing',

//   ],
// spiderSidebar: [
//     'intro2',
//     {
//       type: 'category',
//       label: 'Spider',
//       items: ['spider-basics/create-a-document'],
//     }
//   ],
//   ylacdcpSidebar: [
//     'intro4',
//     {
//       type: 'category',
//       label: 'YLAC DCP',
//       items: ['ylac-dcp/what-is-ylac-dcp'],
//     }
//   ],      
//   qaprocessSidebar: [
//     'intro-qa-process',
//     {
//       type: 'category',
//       label: 'QA Process',
//       items: [
//         {
//           type: 'category',
//           label: 'PHPStan',
//           items: [
//             'qa-process/php-stan',
//             'qa-process/advantage_of_phpstan',
//           ],
//         },
//         'qa-process/psr',
//         'qa-process/mochawesome',
//         'qa-process/ci-cd-pipelines',
//       ],
//     },
//   ],      
// };

// export default sidebars;

// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // spiderSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: "category",
      label: "Admin",
      items: ["admin/project-guide"],
    },
    {
      type: "category",
      label: "User",
      items: ["user/project-guide"],
    },
  ],
  keypointsSidebar: [
    'process',
    {
      type: 'category',
      label: 'Key Points',
      items: ['key-points/brd-key-points',
        'key-points/srs-key-points',
      'key-points/stakeholder-discussions',
    'key-points/scope-timeline',
    'key-points/ui-ux-references',
    'key-points/outcome'],
    },
    'key-points/phase-2-design-specification',
    'node-js/node-js-project-testing',

  ],
spiderSidebar: [
    'intro2',
    {
      type: 'category',
      label: 'Spider',
      items: ['spider-basics/create-a-document'],
    }
  ],
  ylacdcpSidebar: [
    'intro4',
    {
      type: 'category',
      label: 'YLAC DCP',
      items: ['ylac-dcp/what-is-ylac-dcp'],
    }
  ],      
  qaprocessSidebar: [
    'intro-qa-process',
    {
      type: 'category',
      label: 'QA Process',
      items: [
        {
          type: 'category',
          label: 'PHPStan',
          items: [
            'qa-process/php-stan',
            'qa-process/advantage_of_phpstan',
          ],
        },
        'qa-process/psr',
        'qa-process/mochawesome',
        'qa-process/ci-cd-pipelines',
      ],
    },
  ],      
};

export default sidebars;
